name: moviflix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.3
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_database: ^10.4.4
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: PoorStory
      fonts:
        - asset: assets/fonts/PoorStory-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoCondensed-Italic-VariableFont_wght.ttf
          style: italic
    - family: SingleDay
      fonts:
        - asset: assets/fonts/SingleDay-Regular.ttf
