name: moviflix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  cloud_firestore: ^4.15.3
  connectivity_plus: ^5.0.2
  firebase_app_check: ^0.2.1+13
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_database: ^10.4.4
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.2.0
  image_picker: ^1.0.7
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: PoorStory
      fonts:
        - asset: assets/fonts/PoorStory-Regular.ttf
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoCondensed-Italic-VariableFont_wght.ttf
          style: italic
    - family: SingleDay
      fonts:
        - asset: assets/fonts/SingleDay-Regular.ttf
